name: mobile_app
description: A mobile client for your backend.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.6 # or latest version

  # State management
  flutter_riverpod: ^2.5.0

  # FB Sign-in
  flutter_facebook_auth: ^7.1.2

  # Google Sign-in
  google_sign_in: ^6.2.1

  # Simulate iOS notifications
  flutter_local_notifications: ^17.0.0

  # Effects
  smooth_page_indicator: ^2.0.0

  # Calandar
  table_calendar: ^3.0.9

  # HTTP client with interceptors
  dio: ^5.5.0

  # JWT decode
  jwt_decoder: ^2.0.1

  # Firebase core
  firebase_core: ^4.3.0

  # Firebase messaging
  firebase_messaging: ^16.1.0

  # Secure token storage
  flutter_secure_storage: ^9.2.1

  # Load .env file
  flutter_dotenv: ^5.1.0

  # Routing
  go_router: ^14.2.0

  # Time handling
  intl: ^0.19.0
  timezone: ^0.9.2

  # UI / Utils
  google_fonts: ^6.2.1
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/open_image.png
    - assets/home_image.png
    - assets/google_logo.svg
    - .env
