name: mobile_app
description: A mobile client for your backend.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.0

  # HTTP client with interceptors
  dio: ^5.5.0

  # JWT decode
  jwt_decoder: ^2.0.1

  # Secure token storage
  flutter_secure_storage: ^9.2.1

  # Load .env file
  flutter_dotenv: ^5.1.0

  # Routing
  go_router: ^14.2.0

  # UI / Utils
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
